// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SessionManagement.Infrastructure.Persistence;

#nullable disable

namespace SessionManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SessionManagementDbContext))]
    [Migration("20260603135849_AddEvidenceSubmissionsAndTeamProgress")]
    partial class AddEvidenceSubmissionsAndTeamProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("session_management")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.EvidenceSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MissionStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SessionTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SessionTeamId");

                    b.HasIndex("LiveSessionId", "SessionTeamId", "MissionStageId")
                        .HasDatabaseName("ix_evidence_submissions_live_session_team_stage");

                    b.ToTable("evidence_submissions", "session_management");
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.LiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EnrollmentWindowClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_window_closed_at_utc");

                    b.Property<DateTimeOffset?>("EnrollmentWindowOpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_window_opened_at_utc");

                    b.Property<string>("JoinCodeValue")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("join_code_value");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("ScheduledStartAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SessionStageFlowJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("JoinCodeValue")
                        .IsUnique()
                        .HasDatabaseName("ix_live_sessions_join_code_value")
                        .HasFilter("join_code_value IS NOT NULL");

                    b.HasIndex("MissionId");

                    b.ToTable("live_sessions", "session_management");
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.SessionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("LiveSessionId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_session_teams_live_session_id_normalized_name");

                    b.ToTable("session_teams", "session_management");
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.SessionTeamProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStageIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionTeamId");

                    b.HasIndex("LiveSessionId", "SessionTeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_team_progressions_live_session_id_session_team_id");

                    b.ToTable("session_team_progressions", "session_management");
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.TeamParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParticipantUserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SessionTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionTeamId");

                    b.HasIndex("LiveSessionId", "ParticipantUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_participations_live_session_id_participant_user_id");

                    b.ToTable("team_participations", "session_management");
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.EvidenceSubmission", b =>
                {
                    b.HasOne("SessionManagement.Domain.LiveSessions.LiveSession", null)
                        .WithMany("EvidenceSubmissions")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionManagement.Domain.LiveSessions.SessionTeam", null)
                        .WithMany()
                        .HasForeignKey("SessionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.SessionTeam", b =>
                {
                    b.HasOne("SessionManagement.Domain.LiveSessions.LiveSession", null)
                        .WithMany("SessionTeams")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.SessionTeamProgress", b =>
                {
                    b.HasOne("SessionManagement.Domain.LiveSessions.LiveSession", null)
                        .WithMany("TeamProgressions")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionManagement.Domain.LiveSessions.SessionTeam", null)
                        .WithMany()
                        .HasForeignKey("SessionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.TeamParticipation", b =>
                {
                    b.HasOne("SessionManagement.Domain.LiveSessions.LiveSession", null)
                        .WithMany("TeamParticipations")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionManagement.Domain.LiveSessions.SessionTeam", null)
                        .WithMany()
                        .HasForeignKey("SessionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SessionManagement.Domain.LiveSessions.LiveSession", b =>
                {
                    b.Navigation("EvidenceSubmissions");

                    b.Navigation("SessionTeams");

                    b.Navigation("TeamParticipations");

                    b.Navigation("TeamProgressions");
                });
#pragma warning restore 612, 618
        }
    }
}
