<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MediatR" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScoringMonitoring.Application\ScoringMonitoring.Application.csproj" />
    <ProjectReference Include="..\ScoringMonitoring.Domain\ScoringMonitoring.Domain.csproj" />
    <ProjectReference Include="..\..\..\shared\Umbral.ServiceDefaults\Umbral.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ScoringMonitoring.IntegrationTests" />
    <InternalsVisibleTo Include="ScoringMonitoring.UnitTests" />
  </ItemGroup>
</Project>