FROM node:22-alpine AS build
WORKDIR /app

COPY src/apps/web/package.json src/apps/web/package-lock.json ./
RUN npm ci
COPY src/apps/web/ ./

ARG KEYCLOAK_REALM
ARG KEYCLOAK_WEB_CLIENT_ID
ARG NEXT_PUBLIC_EDGE_PROXY_BASE_URL
ARG NEXT_PUBLIC_KEYCLOAK_BASE_URL
ARG NEXT_PUBLIC_SESSION_OPERATIONS_HUB_PATH
ARG NEXT_PUBLIC_SCORING_MONITORING_HUB_PATH
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV KEYCLOAK_REALM=$KEYCLOAK_REALM \
    KEYCLOAK_WEB_CLIENT_ID=$KEYCLOAK_WEB_CLIENT_ID \
    NEXT_PUBLIC_EDGE_PROXY_BASE_URL=$NEXT_PUBLIC_EDGE_PROXY_BASE_URL \
    NEXT_PUBLIC_KEYCLOAK_BASE_URL=$NEXT_PUBLIC_KEYCLOAK_BASE_URL \
    NEXT_PUBLIC_SESSION_OPERATIONS_HUB_PATH=$NEXT_PUBLIC_SESSION_OPERATIONS_HUB_PATH \
    NEXT_PUBLIC_SCORING_MONITORING_HUB_PATH=$NEXT_PUBLIC_SCORING_MONITORING_HUB_PATH \
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
RUN npm run build

FROM nginx:1.27-alpine AS runtime
COPY deployment/docker/nginx-web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 8080
HEALTHCHECK --interval=15s --timeout=3s --retries=3 CMD wget -q -O /dev/null http://127.0.0.1:8080/ || exit 1
