// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbral.ScoringAudit.Api.Infrastructure;

#nullable disable

namespace Umbral.ScoringAudit.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ScoringAuditDbContext))]
    [Migration("20260603210119_AddScoringTables")]
    partial class AddScoringTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scoring_ops")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umbral.ScoringAudit.Api.Domain.Scoreboards.ScoreEntry", b =>
                {
                    b.Property<Guid>("ScoreEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("score_entry_id");

                    b.Property<int>("AccumulatedScoreAfter")
                        .HasColumnType("integer")
                        .HasColumnName("accumulated_score_after");

                    b.Property<int>("AccumulatedScoreBefore")
                        .HasColumnType("integer")
                        .HasColumnName("accumulated_score_before");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<Guid?>("MissionStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_stage_id");

                    b.Property<Guid?>("PenaltyCommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("penalty_command_id");

                    b.Property<Guid?>("PenaltyId")
                        .HasColumnType("uuid")
                        .HasColumnName("penalty_id");

                    b.Property<string>("PenaltySeverity")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("penalty_severity");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<TimeSpan?>("ResolutionTime")
                        .HasColumnType("interval")
                        .HasColumnName("resolution_time");

                    b.Property<Guid>("SessionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_team_id");

                    b.Property<int>("VisibleScoreAfter")
                        .HasColumnType("integer")
                        .HasColumnName("visible_score_after");

                    b.Property<int>("VisibleScoreBefore")
                        .HasColumnType("integer")
                        .HasColumnName("visible_score_before");

                    b.HasKey("ScoreEntryId");

                    b.HasIndex("LiveSessionId")
                        .HasDatabaseName("ix_score_entries_live_session_id");

                    b.HasIndex("LiveSessionId", "SessionTeamId")
                        .HasDatabaseName("ix_score_entries_live_session_id_session_team_id");

                    b.HasIndex("LiveSessionId", "SessionTeamId", "MissionStageId")
                        .IsUnique()
                        .HasDatabaseName("ux_score_entries_single_stage_credit")
                        .HasFilter("mission_stage_id IS NOT NULL AND entry_type IN ('StageCredit', 'ValidationOverrideCredit')");

                    b.ToTable("score_entries", "scoring_ops");
                });

            modelBuilder.Entity("Umbral.ScoringAudit.Api.Domain.Scoreboards.Scoreboard", b =>
                {
                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.HasKey("LiveSessionId");

                    b.ToTable("scoreboards", "scoring_ops");
                });

            modelBuilder.Entity("Umbral.ScoringAudit.Api.Domain.Scoreboards.ScoreEntry", b =>
                {
                    b.HasOne("Umbral.ScoringAudit.Api.Domain.Scoreboards.Scoreboard", null)
                        .WithMany("ScoreEntries")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.ScoringAudit.Api.Domain.Scoreboards.Scoreboard", b =>
                {
                    b.Navigation("ScoreEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
