global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Umbral.ServiceDefaults;
global using ScoringAudit.Application.Abstractions;
global using ScoringAudit.Application.Features.Audit;
global using ScoringAudit.Application.Features.Rankings;
global using ScoringAudit.Application.Features.Scoreboards;
global using ScoringAudit.Application.Hubs;
global using ScoringAudit.Infrastructure.Persistence;
