<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SessionOperations.Application\SessionOperations.Application.csproj" />
    <ProjectReference Include="..\SessionOperations.Infrastructure\SessionOperations.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared\Umbral.ServiceDefaults\Umbral.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>